### ISSUE TITLE
Add ability to pass attributes to consumer mount method for setting on iframe

### ISSUE THREAD

**Issue by nb-gandhi** [cerner/xfc#10]
Please fill out the below template as best you can.
--------------------------------------------------------

### Description of Issue
Starting from version 64, Chrome is deprecating permissions in cross origin iframes. Hence, iframe needs to have allow attribute where permissions can be set. [Reference](https://dev.chromium.org/Home/chromium-security/deprecating-permissions-in-cross-origin-iframes).

So, mount method in consumer has to allow passing attributes and ultimately set it on the iframe created [here](https://github.com/cerner/xfc/blob/master/src/consumer/frame.js#L120).

### Expected Outcomes
- mount() allows the attributes to be passed and sets it on the iframe.

**Comment by mhemesath** [comment]
I think this sounds like a reasonable enhancement.

**Comment by mhemesath** [comment]
@mjhenkes let me know if you have any concerns within this enhancement.

**Comment by kafkahw** [comment]
This issue should be resolved with this PR #11
