### ISSUE TITLE
Getting script error 'hasAttribute' method or property undefined in IE7

### ISSUE THREAD

**Issue by srinivasu-kolli** [cerner/xfc#40]
Please fill out the below template as best you can.
--------------------------------------------------------

### Description of Issue
Getting script error 'hasAttribute' method or property undefined when our application is rendered in IE7. nil checks need to added around the hasAttribute property/method usage in provider.js file. 

<img width="505" alt="image" src="https://user-images.githubusercontent.com/38082976/62336358-f2ed1680-b49d-11e9-9f48-c7e674ef2ed7.png">

### System Configuration
IE7
### Steps to Reproduce the Issue
1. This library is included in cerner-smart-embeddable-library which is used by Cerner Smart Apps. 
2. When our smart app is loading, this java script error pops up.

### Expected Outcomes
- Javascript errors should not be present

**Comment by mjhenkes** [comment]
Hi @srinivasu-kolli, unfortunately xfc does not support any IE version older than 10.
See our browser support here:
https://github.com/cerner/xfc#browser-support
