### ISSUE TITLE
Eliminate the need to challenge the consumer when route protected

### ISSUE THREAD

**Issue by poloka** [cerner/xfc#5]
Please fill out the below template as best you can.
--------------------------------------------------------

### Description of Issue
If the route to mount a content provider is protected by some other means, such as OAuth header validation, there is no need to challenge the consumer for a secret.  In this casethe Provider.init will not contain a secret but only ['*'] to embed into its calling consumer.  The existing Application.launch has a [check](https://github.com/cerner/xfc/blob/6ee99dcb2436aeba2e877d0f0aeb5fd63504726a/src/provider/application.js#L133-L137) against the presence of the secret but if one doesn't exist, as the example provides there is not an else noted at this [point](https://github.com/cerner/xfc/blob/6ee99dcb2436aeba2e877d0f0aeb5fd63504726a/src/provider/application.js#L137)
```
} else { 
  this.authorizeConsumer();
}
```

### Expected Outcomes
- Expect the challenge to the consumer is not executed
- A log message can be displayed indicating the decision to authorize the consumer

**Comment by mhemesath** [comment]
> If the route to mount a content provider is protected by some other means, such as OAuth header validation, there is no need to challenge the consumer for a secret.

Technically all our apps are protected by other means... The question is once the content has been loaded, if I navigate away and go to a malicious site, are they able to to embed this app? How are you preventing that from happening?

**Comment by poloka** [comment]
If the initial page loads and authorizes itself to be displayed, how would the existing consumer challenge eliminate the ability to navigate to other page within that iFramed window?

**Comment by poloka** [comment]
Talked through with @slor on idea as well.  If the challenge is not provided that any consumer would be able to embed the content of the document served by the provider; however, in this case the document is not even served if the cloud oauth validation (server side) does not succeed.  So for a content provider to ignore the challenge could open themselves up to click-jacking only if they do not protect them in some other secure fashion.  Maybe that was more of the question being asked.

**Comment by poloka** [comment]
@whitehatguy, thinking through this security idea, wanted to get your thoughts to if we're opening any holes?

**Comment by poloka** [comment]
To add a bit more information, what we have discovered is that the communications across the iframe are delayed and sporadic. I've seen the challengeConsumer take anywheres from ~100 ms to upwards of 5+ seconds.  Only speculating but possible because of the event loop restrictions within the client consumer.  Looking for ways to improve the performance.

**Comment by mhemesath** [comment]
FWIW `this.authorizeConsumer()` is a public method you can call yourself. Though I recommend against it cause I'm not confident you're preventing any UI redress attacks.

**Comment by kafkahw** [comment]
Fixed in #12
