### ISSUE TITLE
Allow the consumer to skip the mounting lifecycle so that he can reuse the same frame

### ISSUE THREAD

**Issue by sdivi** [cerner/xfc#7]
Please fill out the below template as best you can.
--------------------------------------------------------

### Description of Issue
As  a consumer of xfc i should be able to skip the mounting lifecycle so that i can reuse the same iframe and go through the remaining life cycle events of xfc  launched and authorized so that i can skip the costly iframe creation operation

#### Additional Details (optional)
In a use case where we launch the provider using xfc initial life cycle events and in a refresh scenario where we launch the provider with same url with different authentication params i should be able to use the existing frame and go through the launched and authorized state 

### Steps to Reproduce the Issue
1. Launch any provider using xfc lifecycle events which will create a frame. Relaunch the same content provider which will create a new frame

### Expected Outcomes
Ability to reuse the frame by skipping the mounting lifecycle event and go through the remaining lifecycle events

**Comment by sdivi** [comment]
@poloka

**Comment by mhemesath** [comment]
This seems like a reasonable feature to add. If you open a pull request I’d be happy to review and merge it. Thanks!

**Comment by kafkahw** [comment]
This issue will be addressed by this PR #8

**Comment by kafkahw** [comment]
Fixed in PR #8
